name: visage_access
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0

environment:
  sdk: "^3.3.0-279.3.beta"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
